// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIV7cWaX0R0C4NjqXF0UCehtj5AQU2Dfo',
    appId: '1:428427627479:web:b4ae15a312067e09581992',
    messagingSenderId: '428427627479',
    projectId: 'posproject-fb2ff',
    authDomain: 'posproject-fb2ff.firebaseapp.com',
    storageBucket: 'posproject-fb2ff.firebasestorage.app',
    measurementId: 'G-Y1EX3X0YSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLhhN8-DgtDSFOnUe3kQ00w1dKZvz3BuQ',
    appId: '1:428427627479:android:70266862b9fd65cd581992',
    messagingSenderId: '428427627479',
    projectId: 'posproject-fb2ff',
    storageBucket: 'posproject-fb2ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCptwW3lpMnvhY8rvzlcn06rpjxfwPSad4',
    appId: '1:428427627479:ios:d07765a0fda4810a581992',
    messagingSenderId: '428427627479',
    projectId: 'posproject-fb2ff',
    storageBucket: 'posproject-fb2ff.firebasestorage.app',
    iosBundleId: 'com.example.posSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCptwW3lpMnvhY8rvzlcn06rpjxfwPSad4',
    appId: '1:428427627479:ios:d07765a0fda4810a581992',
    messagingSenderId: '428427627479',
    projectId: 'posproject-fb2ff',
    storageBucket: 'posproject-fb2ff.firebasestorage.app',
    iosBundleId: 'com.example.posSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIV7cWaX0R0C4NjqXF0UCehtj5AQU2Dfo',
    appId: '1:428427627479:web:4ad2d5a2064a0c9d581992',
    messagingSenderId: '428427627479',
    projectId: 'posproject-fb2ff',
    authDomain: 'posproject-fb2ff.firebaseapp.com',
    storageBucket: 'posproject-fb2ff.firebasestorage.app',
    measurementId: 'G-2EH22GQ6P3',
  );
}
